#!/bin/bash

SUBMIT_FLAGS="--interactive"
if [ -n "$GIT_POST_SUBMIT_FLAGS" ]; then
    SUBMIT_FLAGS="$GIT_POST_SUBMIT_FLAGS"
fi
if echo "$2" | grep -q "/"; then
    JIRA="yes"
    ORIGIN=`echo $2 | cut -d/ -f1`

    if [ "$2" != "$3" ] && echo "$2" | grep -q "/pull-requests/"; then #pull request
        TRACKING_ORIGIN=`echo $3 | cut -d/ -f1`
        if [ "$ORIGIN" = "$TRACKING_ORIGIN" ]; then
            $HOME/bin/nrdp-service/cli.js --mode stash --from `echo $2 | cut -d/ -f2-` --to `echo $3 | cut -d/ -f2-`
            JIRA="no"
        fi
    fi

    if [ "$JIRA" = "yes" ]; then #jira
        REMOTE=`git remote -v show $ORIGIN | grep '^ *Push *URL: \(.*\)$' | awk '{print $3}'`
        echo "$REMOTE" | grep -q "ssh://git@stash.corp.netflix.com:7999/" && git jira --comment $SUBMIT_FLAGS "$1..$2"
    fi
fi
