#!/bin/sh
if echo "$2" | grep -q "ssh://git@stash.corp.netflix.com:7999/"; then
    z40=0000000000000000000000000000000000000000
    while read local_ref local_sha remote_ref remote_sha; do
	[ "$local_sha" = $z40 ] && continue
	if [ "$remote_sha" = $z40 ]; then # New branch, examine all commits
	    range="$local_sha"
	else # Update to existing branch, examine new commits
	    range="${remote_sha}..${local_sha}"
	fi
	if git ignore check "$range"; then
	    echo "Ignored commit found in $local_ref. Aborted."
	    exit 1
	fi
    done
fi
exit 0
