#!/bin/sh
#if ! git sync --check "$1" >/dev/null 2>&1; then
#    echo "Must sync first!"
#    exit 1
#fi
if [ -z "$GIT_IGNORE_IGNORE" ] && ! git ignore-commit remote push "$2"; then
    echo "To bypass, export GIT_IGNORE_IGNORE=1 while pushing"
    exit 1
fi
exit 0
